### ISSUE TITLE
Create VM values for raw pointers

### ISSUE THREAD

**Issue by kkutsner** [cesanta/v7#316]
What is the plan for an API to create VM values for raw pointers? I see `v7_to_foreign()` but there is no correspond `v7_create_foreign()`. Looking at the source code I found  `v7_pointer_to_value()` - is this something that going to be a public? In the same time I see comment: 
  `/* NOTE(lsm): don't use v7_pointer_to_value, 32-bit ptrs will truncate */`

Please let me know if this is not an appropriate place to put my questions...

**Update:** It looks like the only way is using `v7_create_number(v7, (unsigned long) some_ptr)` I can pass raw pointers to VM. My concern is that there is no way to add a destructor function which will be called when VM value GCeed...

**Comment by cpq** [comment]
OK let's make it the right way. Could you describe your anticipated use case for foreign pointers please?

**Comment by kkutsner** [comment]
Sorry for delay about this - I thought that foreign pointer could be used to store "handles" for 3rdparty libraries or user data. It will be very handy if VM can call user defined destructor when JS object that contains raw pointer is GCing... 
For example, consider following JS code sample:
```
storage = sqlite.open(':mem:')
```
In example above, we create a sqlite database object which is internally a raw pointer to sqlite database handle. This handle should be managed by VM, I mean, when `storage` object become inaccessible it should be properly released by VM by calling correspond sqlite API.

I understand that SQLite is going to be a built-in module, but V7 users might want to develop their own modules. What will be the right way to do that?

Another related thing is a callback functions passed as arguments to a function which is implemented on C side. What is the proper way to call passed JS function from C code?

**Comment by cpq** [comment]
Assigning @mmikulicic on that.
I see that one way of dealing with that is to export a `sqlite.close()` function and let JS developer handle the problem. Similar thing is already done for files: see https://github.com/cesanta/v7/blob/9dbac5cb5ea16e87bb55368b1389f901e733adaa/src/stdlib.c#L320-L324

    $ ./v7 -e 'var fd = File.open("/etc/passwd"); File.close(fd); fd'
    3

Marko, do you think explicit release API is a way to go, or we should provide a GC callback for the C user to let them register destructors?

**Comment by kkutsner** [comment]
The explicit release API is good to force releasing resources, but what if an exception occurs? The proper way to prevent memory leaks will be inserting `try..catch` blocks to call the explicit release API which does not look good. JS developers normally does not care of memory issues and the only explicit release API will force developers do not forget to call the explicit release API...

**Comment by mmikulicic** [comment]
Finalizers look like an easy way for resource management, however they add complexity to the GC and the non deterministic order of execution make them tricky to use in practice (although the single threaded environment makes it easier to reason about).

I think we could do it easily if we limit ourselves to allow finalizers only on thin wrappers of foreign objects, that is objects that in turn cannot contain references to  other JS objects (potentially with finalizers).

An alternative is just use javascript's power to hide the resource acquisition and disposal boilerplate:

```js
var fd = File.open("/etc/passwd");
openFileWith("/etc/passwd", function(fd) {
 // ..
});
```

or a more generic:

```js
function Acquirable(fn, dispose) {
    return function() {
        dispose = dispose || function(){};

        var args = Array.prototype.slice.call(arguments);
        var cb = args.pop();
        var i = fn(args);
        try {
            cb(i);
        } finally {
            dispose(i)
        }
    }
}
guardedFile = Acquirable(File.open, File.close);
guardedFile("/etc/passwd", function(fd) { /* ... */ });
```

Upside: this can be understood and debugged as any other code, and it's portable between JS VMs.
