### ISSUE TITLE
signbit() function leads to compiler issues on Windows using VS2013

### ISSUE THREAD

**Issue by kkutsner** [cesanta/v7#317]
`signbit()` function (defined at v7.c file) leads to compiler issues on Windows using VS2013 (Version 12.0.21004.1). The issue is that signbit function is already defined in math.h. 

If you accept pull requests, I could make a fix for that...

**Comment by cpq** [comment]
PR is welcome, provided you're waving copyright claims and releasing the change under the existing V7 license.

**Comment by cpq** [comment]
In interpreter.c

    #ifdef V7_WINDOWS
    static int signbit(double x) {
      return x > 0;
    }
    #endif

I guess we can change the conditional to

    #if defined(V7_WINDOWS) && _MS_VER > ....

**Comment by kkutsner** [comment]
Probably yes, but we don't know the min value of _MS_VER....

**Comment by cpq** [comment]
https://msdn.microsoft.com/en-us/library/hh308342.aspx says 2013 and 2012 in "other versions."

http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008 has a mapping of years to _MS_VER.

Let's go for 2012, _MS_VER  1700. Sending PR.

**Comment by kkutsner** [comment]
Sergey, I really want to try pull some PRs, and I'm trying to understand what is individual contributor license (http://cesanta.com/contributors_la.shtml) and how to work with that... Do you know where to read about it in plain form (e.g. "для чайников"). Sorry for this off-topic.

**Comment by cpq** [comment]
Тут вроде доступно написано: https://help.github.com/articles/creating-a-pull-request/

**Comment by kkutsner** [comment]
Спасибо:) как готовить PRы, я в курсе:) мне не совсем понятно насчет contributor license - что это и зачем нужно...

**Comment by cpq** [comment]
Это нужно для нашей защиты. Мы обязуемся перед нашими клиентами что наш код принадлежит нам, и мы не украли его у кого-то еще. Если кто-то шлет нам PR, он потенциально может оспорить это и подать на нас в суд. Подписание agreement нас от этого защищает. Вот вики: https://en.wikipedia.org/wiki/Contributor_License_Agreement

Так делают многие проекты - например https://github.com/influxdb, вот их соглашение: http://influxdb.com/community/cla.html
