### ISSUE TITLE
crash with new Date(...)

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#348]
test S15.9.3.1_A5_T5.js crash v7.
actually, for crash enough such expression new Date(1899, 11, 31, 23, 59, 59)

**Comment by mmikulicic** [comment]
Cannot reproduce. Does it happen again? On windows? Which compiler?

**Comment by vrz** [comment]
it's still crash.
win xp, win7.
MinGW

v7 -e "new Date(1899, 11, 31, 23, 59, 59)"
![image](https://cloud.githubusercontent.com/assets/8409104/6655280/44387616-cb09-11e4-9878-d4663c2d5f8c.png)

**Comment by alashkin** [comment]
Is it still crashing?
There was on error in memory allocation, causes undefined behavior, it was fixed a couple of days ago.

**Comment by vrz** [comment]
yes,  it still crashing.

v7 -e "new Date(1899, 11, 31, 23, 59, 59)"


Понедельник, 23 марта 2015, 0:31 -07:00 от Alexander Alashkin <notifications@github.com>:
>Is it still crashing?
>There was on error in memory allocation, causes undefined behavior, it was fixed a couple of days ago.
>—
>Reply to this email directly or  view it on GitHub .



---
Приглашаем пообщаться на www.talk.ru

**Comment by cpq** [comment]
Works fine with my Visual Studio 6 build.

**Comment by mmikulicic** [comment]
Issue reproduced on real windows, with both MSVC6 and VS2013
