### ISSUE TITLE
Make regex and utf8 support optional

### ISSUE THREAD

**Issue by cpq** [cesanta/v7#371]
Add preprosessor conditionals `V7_DISABLE_REGEXP` and `V7_DISABLE_UTF8` - those might save a lot of space.

**Comment by cpq** [comment]
Rojer, please take this over.
As part of your conditional compilation effort, make UTF8 support optional - I think the easiest way is to provide UTF8 stubs, e.g.

    #ifdef V7_DISABLE_UTF8
      implements a subset of utf8 functions that v7 uses using simple stubs
    #else
    #endif

**Comment by rojer** [comment]
this should be it.
some ECMA tests are broken by this but this will be handled when specifying profiles.
