### ISSUE TITLE
too deep stack

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#4]
В parse_expression вызывается parse_logical_or, в которую, в свою очередь, как в матрёшку вложены остальные парсеры: parse_logical_and->parse_bitwise_or->parse_bitwise_xor->etc.
Спору нет, красивое решение.
Но, при использовании во встроенных системах может возникнуть проблема из-за слишком глубокого стека. Может банально не хватить памяти. Ведь место под стек чаще всего выделяется статически и отхватив его слишком много можно обделить всё остальное.
IMHO, правильнее было бы вызывать все парсеры из parse_expression на одном уровне вложенности.

**Comment by mmikulicic** [comment]
Obsolete
