### ISSUE TITLE
`v7_to_json` does not allocate a larger buffer if needed because `to_str` reports only number of bytes written, no number of bytes needed

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#402]
v7 -e "eval('print(111111111111111111111111); print(2222222222222222222222);')"
1.11111111111111109247e+023
2.22222222222222216397e+021
null

v7 -e "eval('print(111111111111111111111111); print(2222222222222222222222); print(333333333333333333333333333);')"
Exec error [eval('print(111111111111111111111111); print(2222222222222222222222); print(333333333333333333333333333);')]: {"message":"parse error at at line 1 col 99: [ print(111111111111111111"}
undefined

**Comment by vrz** [comment]
The same problem there is with Function()

**Comment by vrz** [comment]
problem with Function() was resolved in pull request #429

**Comment by gelraen** [comment]
```
char buf[100], *p;
p = v7_to_json(v7, arg, buf, sizeof(buf));
```
https://github.com/cesanta/v7/blob/master/src/stdlib.c#L36 :)

**Comment by gelraen** [comment]
So the problem is that [to_str](https://github.com/cesanta/v7/blob/master/src/vm.c#L330) does not return the number of bytes needed to serialize the object, as [v7_to_json](https://github.com/cesanta/v7/blob/master/src/vm.c#L528) assumes.

**Comment by gelraen** [comment]
Looks like https://github.com/cesanta/v7/commit/b883409f1d68701b25e530e11a31d30897962420 broke this.

**Comment by gelraen** [comment]
No, it was not returning the number of bytes needed even before that.

**Comment by gelraen** [comment]
It's here: https://github.com/cesanta/v7/commit/844cc313550ed6966d427c5e7d260ac02802b8b5
`v7_to_json` (which did not allocate a new buffer if needed) was renamed to `to_json` and a wrapper around it, named `v7_to_json`, was added, assuming that return value of `to_json` is the number of bytes needed to serialize the full object, while it was the number of bytes written to the buffer.

**Comment by cpq** [comment]
@gelraen good catch

**Comment by gelraen** [comment]
@vrz, please verify that it works for you.
```% ./v7 -e "eval('print(111111111111111111111111); print(2222222222222222222222); print(333333333333333333333333333);')"
1.11111111111111109247e+23
2.22222222222222216397e+21
3.33333333333333314856e+26
null```

**Comment by vrz** [comment]
yes, it works.

v7 -e "eval('print(0.000000000000000000000000000000000000000000000000001); print(111111111111111111111111); print(2222222222222222222222); print(333333333333333333333333333); print(44444444444444444444444444444444444); print(555555555555555555555555555555555555555555); print(6666666666666666666666666666666666666666666666666666666); print(7777777777777777777777777777777777777777777); print(888888888888888888888888888888888888888); print(99999999999999999999999);')"
1e-051
1.11111111111111109247e+023
2.22222222222222216397e+021
3.33333333333333314856e+026
4.44444444444444399759e+034
5.55555555555555563298e+041
6.6666666666666667349e+054
7.77777777777777788618e+042
8.88888888888888868878e+038
9.99999999999999916114e+022
null

**Comment by gelraen** [comment]
Cool, thanks!
