### ISSUE TITLE
Warning in socket.c

### ISSUE THREAD

**Issue by mmikulicic** [cesanta/v7#403]
Recent commits disabled sockets in our build so it compiles on windows. 
(We need better way setting defaults for several platforms in the makefiles, to be tracked in a separate issue)

This revealed a warning:

```
src/socket.c:450:7: warning: ISO C requires a translation unit to contain at least one declaration [-Wempty-translation-unit]
#endif
```

We should fix it in order to avoid us becoming warning blind.

**Comment by alashkin** [comment]
Thank you!
Don't you mind if I fix this bug with new PR (final socket implementation)?

**Comment by mmikulicic** [comment]
No problem!

**Comment by alashkin** [comment]
Fixed with https://github.com/cesanta/v7/pull/410
