### ISSUE TITLE
src/internal.h:59:25: error: sys/utsname.h: No such file or directory

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#441]
MinGW, ver.4.4.5

**Comment by gelraen** [comment]
@vrz, can you try https://github.com/cesanta/v7/tree/uname_fix ?

**Comment by vrz** [comment]
i tried it after merge pull request #443 from cesanta/uname_fix

src/internal.h:80:25: error: sys/utsname.h: No such file or directory

the same problem, but other string number

**Comment by mmikulicic** [comment]
it looks like mingw is not detected as windows by our preprocessor checks

**Comment by gelraen** [comment]
It looks like it was excluded on purpose, so I'll also check MinGW-specific defines.

**Comment by vrz** [comment]
IMO, it would be easier to have NON_POSIX as default, as most embedded systems

**Comment by gelraen** [comment]
Sounds reasonable.

**Comment by gelraen** [comment]
Hm, we don't have preprocessor definitions for anything except Windows and Arduino. @mmikulicic, what do you think about adding `-DV7_NO_POSIX` to `DEFS_WINDOWS` in `platform.mk`?

**Comment by mmikulicic** [comment]
Our goal is that (if possible) sources should build on a target platform without any preprocessor parameter. We ship only the sources and people don't need to know how to add preprocessor flags. Add to the project in whatever IDE and it should compile. Preprocessor flags should enhance (e.g. reduce the size, enable features) and generally are looked after the user has had his first impression of the product.

So if we want to go this way, probably it's better to just invert V7_NO_POSIX to V7_HAS_POSIX, and add V7_HAS_POSIX to the default flags and then add -UV7_HAS_POSIX to the windows (and other non posix builds) overrides.

---

I wonder if some of those windows and arduino specific things are pretty common in non posix systems and we should perhaps group them. We need more non-posix targets to cross-compile to. Any ideas?
