### ISSUE TITLE
build problems on windows

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#457]
make.exe v7

"grep" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
"GENERATING src/features_full.h"
"perl" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
make.exe: *** [src/features_full.h] Error 1

**Comment by mmikulicic** [comment]
I guess somebody does run this on windows.
We should fallback to the checked in file if there is no `perl` on the path

**Comment by vrz** [comment]
make.exe v7

"grep" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Системе не удается найти указанный путь.
scripts/platform.mk:38: *** commands commence before first target.  Stop.

**Comment by rojer** [comment]
can you post output of make --version?

**Comment by vrz** [comment]
make.exe --version

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

This program built for i386-pc-mingw32

**Comment by rojer** [comment]
repor'd with 3.81
sent a PR because it was easy to fix, but please consider updating your toolchain

**Comment by vrz** [comment]
problem not in my tools. problem first of all in portability of v7.
last couple days, every commit made v7 less portable.
all of you doing everything to make it suitable to build in Linux.
it is absolutely WRONG WAY.

**Comment by rojer** [comment]
fixed by #462 

most devs actually work on macs :) but that's not the point.
the point is that the main product, if you will, is v7.c. it will compile and work on all the platforms, but the machinery used to build it (and v7.c is assembled from parts - see the "v7.c" target in the Makefile, for example) is not guaranteed to work on all of them.

**Comment by vrz** [comment]
v7.c not resolve all problems.
v7.c v7.h and must not contain macros, depending on the target platform. They should not contain inclusions of NON ANSI header files.

**Comment by rojer** [comment]
that's a separate issue. has #462 fixed the build for you?

**Comment by vrz** [comment]
yes, it's fixed
