### ISSUE TITLE
incorrect work of operator 'new'

### ISSUE THREAD

**Issue by vrz** [cesanta/v7#482]
node.exe -e "var a = {a:1, b:2, c:3, f:function(){}}; function B(o) {for(p in o) this[p] = o[p];} B.prototype = a; var b = new B({k:5}); console.log(b); for(p in b) console.log(p + ':' + b[p]);"
{ k: 5 }
k:5
a:1
b:2
c:3
f:function (){}

v7.exe -e "var a = {a:1, b:2, c:3, f:function(){}}; function B(o) {for(p in o) this[p] = o[p];} B.prototype = a; var b = new B({k:5}); print(b); for(p in b) print(p + ':' + b[p]);"
{"k":5}
k:5
null

**Comment by 0xae** [comment]
UP,
the same is happening in debian amd64

    ./v7 -e "var a = {a:1, b:2, c:3, f:function(){}}; function B(o) {for(p in o) this[p] = o[p];} B.prototype = a; var b = new B({k:5}); print(b); for(p in b) print(p);"

**Comment by 0xae** [comment]
Trying to investigate the possible cause of this bug

**Comment by RReverser** [comment]
I'm not maintainer of this project, but come on, piece of code is not really a proper issue. Please format the code, describe what you expect, what exactly you're getting and why it is wrong.

**Comment by mmikulicic** [comment]
V7 incorrectly implements https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

it iterates only through owned properties

**Comment by mmikulicic** [comment]
Fixed and pushed
