### ISSUE TITLE
Compilling v7 with g++

### ISSUE THREAD

**Issue by 0xae** [cesanta/v7#489]
Hi, could you guys please help me compile v7 with c++, i opened the Makefile
defined CC=g++, but i am getting some compiler errors.
Also when i compiled v7 with gcc it gave some warns.

here are the errors during c++ compilation:
http://i.imgur.com/93FXbbo.png

thanks in advance

**Comment by cpq** [comment]
Fix is coming.
The problem is that Linux defines L_SET in unistd.h, which conflicts with L_SET enum in v7.c
If you're in hurry, just change L_SET to L_CHSET in v7.c

**Comment by 0xae** [comment]
Okay man, i changed all ocurrences of L_SET with L_CHSET and it compiled fine, with some warnings too but thats just C++ normal complaints.
Thanks a lot
