### ISSUE TITLE
How can i use chaining

### ISSUE THREAD

**Issue by DaveM2011** [cesanta/v7#490]
Hi im having quite a bit of trouble when chaining when chaining methods like new Widget().show(); for example the constructor for Widget is called twice could you maybe give me some pointers thanks

**Comment by DaveM2011** [comment]
```
struct v7 *v7 = v7_create();
v7_val_t ctor_func, proto, eval_result;
proto = v7_create_object(v7);
ctor_func = v7_create_constructor(v7, proto, Widget_ctor, 1);
v7_set_method(v7, proto, "show", &Widget_myMethod);
v7_set(v7, v7_get_global_object(v7), "Widget", ~0, 0, ctor_func);
v7_exec(v7, &eval_result, "var w = new Widget().show();print('Widget = ', w);");
v7_destroy(v7);
```

This shows what i mean :smile:

**Comment by mmikulicic** [comment]
Sorry for the late reply, this slipped through. I reproduced the bug, thanks for reporting!

Reproduced also with pure JS code.

```sh
./v7 -e 'function Widget() { print("ctr") }; Widget.prototype.show = function() { return this}; new Widget().show()'
```

```
ctr
ctr
{}
```

**Comment by DaveM2011** [comment]
Awsome i see you push quite a lot so i suppose it will be fixed quite soon thanks

**Comment by mmikulicic** [comment]
Indeed fixed in 2baaaebc350335872cf150c9ba23227c3aaceb4c

Let me know if it works for you!

**Comment by DaveM2011** [comment]
OK awsome i will

**Comment by DaveM2011** [comment]
Sweet it works perfect thanks lots and lots :smiley:
