### ISSUE TITLE
Can't execute if binary stack size > 65535?

### ISSUE THREAD

**Issue by edvakf** [cesanta/v7#494]
I prepared a file with 5040 lines of `print(1);` and ran with the v7 command. I got 5040 lines of 1 and an `undefined`. Then I added one more line of `print(1);` and I got just one line of output, `undefined`.

I noticed that this is something to do with the second and third bytes of the binary AST as well as the length of it. I couldn't find out the part of the code related to this.

```
$ ./v7/v7 -b ./5040.js | xxd -c 8 | head -n 2
0000000: 01ff f400 004f 000c  .....O..
0000008: 1405 7072 696e 7413  ..print.
$ ./v7/v7 -b ./5040.js | wc -c
65525
```

```
$ ./v7/v7 -b ./5041.js | xxd -c 8 | head -n 2
0000000: 0100 0100 004f 000c  .....O..
0000008: 1405 7072 696e 7413  ..print.
$./v7/v7 -b ./5041.js | wc -c
65538
```

Can someone explain to me what's happening here? Also, is it an expected behavior? Is there a way to have more statements than this?

I use Mac OS X Yosemite.

**Comment by mmikulicic** [comment]
yeah, currently we support only 16-bit offsets in our AST. Our main target are small scripts so I deprioritized this. Anyway, it's a bug and it should be fixed.

**Comment by edvakf** [comment]
Thanks for your reply. Could you point me to where to look for "we support only 16-bit offsets in our AST."?

**Comment by mmikulicic** [comment]
The code that encodes the offset is here: https://github.com/cesanta/v7/blob/master/v7.c#L6276
and other places define the size of the AST nodes based on the fact that the offset size is 2 bytes.

**Comment by edvakf** [comment]
Thanks. I'm gonna close this issue.
