### ISSUE TITLE
function apply arguments always zero

### ISSUE THREAD

**Issue by zeropool** [cesanta/v7#508]
function abc() {
    print(arguments.length);
}

abc(1,2,3); // print 3, right
abc.apply(this, [1,2,3]); // print 0, wrong
abc.call(this, 1,2,3); // print 0, wrong

**Comment by mmikulicic** [comment]
merged in 7390c578cf30d57f108e12ff20c51e8142cd43c6

**Comment by zeropool** [comment]
Your engine is the fastest javascript engine without JIT, good job !!!!!
