### ISSUE TITLE
How to visit array from v7?

### ISSUE THREAD

**Issue by vinjn** [cesanta/v7#515]
```js
var matrixInJS = [1,0,0,0,
              0,1,0,0,
              0,0,1,0,
              0,0,0,1];
Node_setMatrix(matrixInJS);
```

```C++
v7_val_t Node_setMatrix(struct v7 *v7)
{
    float* matrixInC;
    // how to get the value of matrixInC

    return 0;
}

```

Thanks.

**Comment by vinjn** [comment]
Maybe some function like this?
```C
const void *v7_to_array(struct v7 *, v7_val_t *value);
```

**Comment by mmikulicic** [comment]
Sorry, dense arrays are an implementation detail at the moment and we don't export a pointer to a contiguous piece of memory containing array values. 

V7 exposes only the JS data model to C.

Please iterate over the array with `v7_array_get` and `v7_array_length`.

**Comment by vinjn** [comment]
OK, thx.
