### ISSUE TITLE
v7_set_method() doesn't have a 'num_args' argument

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#526]
That's confusing IMO: why do `v7_create_function()` and `v7_create_constructor()` require `num_args` while `v7_set_method()` does not while it's a wrapper to the former? For API consistency, they should all have `num_args` IMO.

Furthermore: looking at the code, it appears `v7_create_function()` accepts `-1` as the number of arguments, which is what `v7_set_method()` does. What is `num_args` for anyway and what the special value `-1` for? It'd be great to have this explained in the docs.

**Comment by cpq** [comment]
Marko pls take care of this one

**Comment by mmikulicic** [comment]
We removed the num_args argument in create_function and create_constructor as it's only useful when creating stdlib functions.

If anybody needs it, it can be set with `v7_set` as with any other property.
