### ISSUE TITLE
Why is v7_to_string() taking a v7_val_t* instead of a v7_val_t?

### ISSUE THREAD

**Issue by swisspol** [cesanta/v7#530]
As far as I can tell, the implementation of v7_to_string() does not reassign the pointer.

This prevents doing a simple `v7_to_string(v7, v7_array_get(v7, args, 0), NULL)`.

**Comment by cpq** [comment]
Because short strings (<= 5 bytes) are inlined into the NaN payload, i.e. a string is inside v7_val_t. Since v7_val_t is passed by value to `v7_to_string`, we cannot return an address pointing inside it.

**Comment by swisspol** [comment]
Ah, can't believe I missed that!
