### ISSUE TITLE
Object enumeration in C

### ISSUE THREAD

**Issue by wenq1** [cesanta/v7#545]
I have a JS object var testobj {a: 'test1', b: 'test2'} the keys of which I would like to enumerate in C. This is particularly useful if I want to set header fields for HTTP requests. In JS I know I can do:

    for (var i in testobj) do {
        printLog ('key': i, 'val': testobj[i]
    }

I wonder is there an enumeration function in v7's native C API allowing me to enumerate v7_val_t?

**Comment by cpq** [comment]
`v7_next_prop()` is the API you're looking for.
