### ISSUE TITLE
GPLv2

### ISSUE THREAD

**Issue by ekiwi** [cesanta/v7#565]
Hi,

I might be wrong, but I think you are misinterpreting the GPLv2 license in your readme:

> Commercial Projects: Once your project becomes commercialised GPLv2 licensing dictates that you 
> need to either open your source fully or purchase a commercial license. 

The GPLv2 does not restrict you in selling your code nor does it force you to "fully" open source your code. It only makes sure that people who receive a binary of a GPLv2 program also have access to its source code. So if you sell only to a selected number of users you only need to make the source code available to them.

The official [GPLv2 FAQ](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#GPLCommercially) has the following to say about commercial redistribution:

> You are allowed to sell copies of the modified program commercially, but only under the terms of the GNU GPL. Thus, for instance, you must make the source code available to the users of the program as described in the GPL, and they must be allowed to redistribute and modify it as described in the GPL. 

It would be great if you could reevaluate your interpretation of the GPLv2 and check if you might want to adjust the explanation given in your readme.

eKiwi

**Comment by cpq** [comment]
Thank you @ekiwi . I do not see a problem with our interpretation.
