### ISSUE TITLE
Object access from API

### ISSUE THREAD

**Issue by ScriptBasic** [cesanta/v7#567]
How does one access an object created in JavaScript code from the API? The properties have a name which I assume I can access them from the API using them.

**Comment by dimonomid** [comment]
Yes, take a look at [v7_get()](https://docs.cesanta.com/v7/master/#/c-api/object_public.h/v7_get.md/).

**Comment by ScriptBasic** [comment]
v7_get() only retrieves the properties. I need a way to access the object 'handle' that was created in JavaScript code from my 'C' program.
