### ISSUE TITLE
unit_test fails

### ISSUE THREAD

**Issue by 0rel** [cesanta/v7#570]
unit_test failed after building the freshly cloned project:
<pre>
$ make
...
cd tests; TZ=UTC ./unit_test
...
  [0.000] test_user_data
foo 
Expected: {"stack":"    at myFunc (Eval'd code:1)\n    at Eval'd code:1\n    at cfunc\n    at <anonymous> (test_expr:4)\n    at test_expr:3","message":"[d] is not defined"}
Actual  : {"stack":"    at myFunc (Eval'd code:1)\n    at Eval'd code:1\n    at cfunc_0x44f490\n    at <anonymous> (test_expr:4)\n    at test_expr:3","message":"[d] is not defined"}
tests/unit_test.c:4297:1 [ASSERT_EVAL_EQ("var err;\n" "try {\n" "  (function () { \n" "    eval('function myFunc(){d}; myFunc();')\n" "  })()\n" "} catch (e) { err = e; }\n" "err;\n", "({" "'message': '[d] is not defined'," "'stack':\"" "    at myFunc (Eval'd code:1)\\n" "    at Eval'd code:1\\n" "    at cfunc\\n" "    at <anonymous> (test_expr:4)\\n" "    at test_expr:3" "\"})")] (in test_exec_generic)
  [0.005] test_exec_generic
FAIL, run 3660 in 0.132s
make: *** [Makefile:16: test] Error 1
</pre>

`cfunc_0x44f490 <-> cfunc`:
It has to do with the name of an anonymous function, so this seems to be a really minor issue.

**Comment by 0rel** [comment]
Defining V7_FILENAMES_SUPPRESS_CFUNC_ADDR in the Makefile fixed the issue:
V7_FLAGS = -DCS_ENABLE_UTF8 -DV7_FILENAMES_SUPPRESS_CFUNC_ADDR

**Comment by mmikulicic** [comment]
thanks for reporting this. Which compiler are you using? Which arch (cpu, 32/64 bit?)

**Comment by mmikulicic** [comment]
ah, sorry; I just replied with a canned response, but the issue here is obvious:

In order to make our tests match a stable output (i.e. not contain addresses suck as `cfunc_0x44f490`), we need  `DV7_FILENAMES_SUPPRESS_CFUNC_ADDR` while building the unit tests, but the public Makefile was outdated.
