### ISSUE TITLE
Can I run under iOS? And  Is it thread safe?

### ISSUE THREAD

**Issue by yemingyu** [cesanta/v7#583]

**Comment by adminy** [comment]
I have it jail-broken so I attempted to compile it with gcc. I get enormous amount of errors ... its like everything just won't work. However I compiled it for raspberry Pi (also ARM processor) worked just fine. So maybe ios gcc is outdated? Here is the logs of the gcc and all the errors. If you can fix them all then I can compile for ios.
[logs.txt](https://github.com/cesanta/v7/files/1099956/logs.txt)

**Comment by cpq** [comment]
we have stopped v7 development in favor for https://github.com/cesanta/mjs.

v7 and mjs are not thread safe.
